


`r 
#set up the data.


#create a variable containing all the year options. (no edit needed)

Year <- levels(as.factor(EEFlatest$Year))


#create the latest year as a variable (no edit needed)

latestyear <- filter(graphData, Year==max(Year), Measure == "Count of Early Learning and Childcare registrations, September",
                            Characteristic == "Age")$Year[1]


#create the last year as a variable (no edit needed)

lastyear <- filter(graphData, Measure == "Count of Early Learning and Childcare registrations, September",
                            Characteristic == "Age", Year == latestyear-1)$Year

#create the latest year's data for the number of elc registrations (no edit needed)

Count_of_elc_latest <- as.numeric(filter(graphData, Year==max(Year), Measure == "Count of Early Learning and Childcare registrations, September",
                                      Characteristic == "Age", Breakdown == "All")$Figure)

# Count_of_elc_latest formatted so it appears without scientific notation

Count_elc_latest <- format(Count_of_elc_latest,scientific=FALSE,big.mark=",")


#create the previous year's data for the number of elc registrations (no edit needed)

Count_of_elc_last <- as.numeric(filter(graphData, Measure == "Count of Early Learning and Childcare registrations, September",
                                      Characteristic == "Age", Breakdown == "All", Year == latestyear-1)$Figure)
# Count_of_elc_last formatted so it appears without scientific notation

Count_elc_last <- format(Count_of_elc_last,scientific=FALSE,big.mark=",")


#calculate the difference from the previous year

Difference <- Count_of_elc_latest - Count_of_elc_last

#convert difference to positive if below 0

Difference2 <- if (Difference < 0) {
Difference * - 1
} else 
{Difference
}


#change the wording based on the difference

increase_decrease <- if (Difference < 0) {
"a decrease of"
} else if (Difference > 0) {
"an increase of"
} else {
"a change of"
}

#writen text. No edit needed, it should update with above.

`

* In `r latestyear`, there were `r Count_elc_latest` registrations for early learning and childcare in Scotland.
	This represents `r increase_decrease` `r format(Difference2,big.mark=",",scientific=FALSE)` from the `r lastyear` figure of `r Count_elc_last`.
	Most registrations are for 3 and 4 year olds, with smaller numbers of 2 year olds and under and children who defer entry to primary school.
	
